In [31]:
from pylab import *
from numpy import *
D=loadtxt('elv.txt')
#짝수층 엘리베이터
eupin=zeros((6,1))
eupout=zeros((6,1))
edwin=zeros((6,1))
edwout=zeros((6,1))
#홀수층 엘리베이터
oupin=zeros((6,1))
oupout=zeros((6,1))
odwin=zeros((6,1))
odwout=zeros((6,1))
for i in range(5):
    oupin[i]=D[i*2,1]
    oupout[i]=D[i*2,2]
    odwin[i]=D[i*2,3]
    odwout[i]=D[i*2,4]
    eupin[i+1]=D[(i*2+1),1]
    eupout[i+1]=D[(i*2+1),2]
    edwin[i+1]=D[(i*2+1),3]
    edwout[i+1]=D[(i*2+1),4]
    #올라갈때 1층에서 내리는 사람과 내려올때 1층에서 타는 사람을 뺌
    eupout[0]=0
    edwin[0]=0
    oupout[0]=0
    odwin[0]=0

In [32]:
#10층으로 가려는 사람이 각 엘리베이터에 절반씩 탄다고 가정
oupout[5]=eupout[5]//2
eupout[5]=eupout[5]-oupout[5]
#1층에서 타는 사람 계산(2~10층에서 내리는사람 - 2~9층에서 타는 사람)
eupin[0]=sum(eupout[1:6])-sum(eupin[1:5])
oupin[0]=sum(oupout[1:6])-sum(oupin[1:5])
k=0
#10층에서 타려는 사람은 먼저 도착하는 걸 타게 하기 위해 나중에 정하려고 우선 10층에서 타는 사람을 0으로 만듬
upin5=0
upin5=int(eupin[5])
eupin[5]=0
edwout[0]=edwout[0]-edwin[5]
edwin[5]=0
#1층에서 내리는 사람 수 계산
edwout[0]=sum(edwin[1:5])-sum(edwout[1:4])
odwout[0]=sum(odwin[1:5])-sum(odwout[1:4])

In [33]:
eupinst=zeros((6,1))
eupoutst=zeros((6,1))
edwinst=zeros((6,1))
edwoutst=zeros((6,1))
oupinst=zeros((6,1))
oupoutst=zeros((6,1))
odwinst=zeros((6,1))
odwoutst=zeros((6,1))
for i in range(6):
    #올라가는 짝수엘베의 1,0
    if eupin[i]>=1:
        eupinst[i]=1
    if eupout[i]>=1:
        eupoutst[i]=1
    #올라가는 홀수엘베의 1,0
    if oupin[i]>=1:
        oupinst[i]=1
    if oupout[i]>=1:
        oupoutst[i]=1

In [34]:
eupst=zeros((6,1))
edwst=zeros((6,1))
oupst=zeros((6,1))
odwst=zeros((6,1))
for i in range(6):
    #올라갈때 타거나 내리려는 사람이 있고, 엘베 안이 19명 이하라면 오픈
    if eupinst[i]+eupoutst[i]>0 and sum(eupin[:(i+1)])-sum(eupout[:(i+1)])<=19:
        eupst[i]=1
    if oupinst[i]+oupoutst[i]>0 and sum(oupin[:(i+1)])-sum(oupout[:(i+1)])<=19:
        oupst[i]=1

In [35]:
#10층에 더 빨리 도착하는 게 10층에서 타려는 사람들을 태운다.
if sum(eupst[:5])>sum(oupst[:5]):
    odwin[5]=upin5
    odwout[0]=odwout[0]+odwin[5]
else:
    edwin[5]=upin5
    edwout[0]=edwout[0]+edwin[5]

In [36]:
for i in range(6):
    #내려가는 짝수엘베의 1,0
    if edwin[i]>=1:
        edwinst[i]=1
    if edwout[i]>=1:
        edwoutst[i]=1
    #내려가는 홀수엘베의 1,0
    if odwin[i]>=1:
        odwinst[i]=1
    if odwout[i]>=1:
        odwoutst[i]=1

In [37]:
for i in range(6):
    #내려갈때 타거나 내리려는 사람이 있고, 엘베 안이 19명 이하라면 오픈
    if edwinst[i]+edwoutst[i]>0 and sum(edwin[(i+1):])-sum(edwout[(i+1):])<=19:
        edwst[i]=1
    if odwinst[i]+odwoutst[i]>0 and sum(odwin[(i+1):])-sum(odwout[(i+1):])<=19:
        odwst[i]=1

In [38]:
k=0
l=0
m=0
n=0
#엘베 정원이 초과라서 못 탄 사람들
for i in range(6):
    k=k+eupin[i]-eupout[i]
    l=l+edwin[5-i]-edwout[5-i]
    eupin[i]=0
    edwin[5-i]=0
    if k>19:
        while k>19:
            k=k-1
            eupin[i]=eupin[i]+1
    if l>19:
        while l>19:
            l=l-1
            edwin[5-i]=edwin[5-i]+1
    m=m+oupin[i]-oupout[i]
    n=n+odwin[5-i]-odwout[5-i]
    oupin[i]=0
    odwin[5-i]=0
    if m>19:
        while m>19:
            m=m-1
            oupin[i]=oupin[i]+1
    if n>19:
        while n>19:
            n=n-1
            odwin[5-i]=odwin[5-i]+1
eupout=zeros((6,1))
edwout=zeros((6,1))
oupout=zeros((6,1))
odwout=zeros((6,1))

In [39]:
#못 탄 사람들
print(transpose(eupin))
print(transpose(edwin))
print(transpose(oupin))
print(transpose(odwin))

[[0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]]


In [40]:
#각 층 사이에서 걸리는 시간
#멈추면 그 전전층에서 현재 층까지 10초, 안 멈추면 그 전전층에서 현재층까지 4초
eupf=[]
edwf=[]
oupf=[]
odwf=[]
for i in range(6):
    if eupst[i]==1:
        eupf.append(i+1)
    if edwst[i]==1:
        edwf.append(i+1)
    if oupst[i]==1:
        oupf.append(i+1)
    if odwst[i]==1:
        odwf.append(i+1)
eupl=len(eupf)
edwl=len(edwf)
eupt=0
edwt=0
oupl=len(oupf)
odwl=len(odwf)
oupt=0
odwt=0
#open인층에서 다음 open인 층까지의 시간 계산
for i in range(eupl-1):
    eupt=eupt+(eupf[i+1]-eupf[i]-1)*4+10
for i in range(edwl-1):
    edwt=edwt+(edwf[i+1]-edwf[i]-1)*4+10
for i in range(oupl-1):
    oupt=oupt+(oupf[i+1]-oupf[i]-1)*4+10
for i in range(odwl-1):
    odwt=odwt+(odwf[i+1]-odwf[i]-1)*4+10

In [41]:
edwst[5]=0
odwst[5]=0
eupop=0
edwop=0
oupop=0
odwop=0
#각 층에서 오픈이면 12초씩 추가
for i in range(6):
    if eupst[i]==1:
        eupop=eupop+12
    if edwst[i]==1:
        edwop=edwop+12
    if oupst[i]==1:
        oupop=oupop+12
    if odwst[i]==1:
        odwop=odwop+12
etime=eupop+edwop+eupt+edwt
otime=oupop+odwop+oupt+odwt
print(etime,otime)

138 186


In [42]:
#1층에서 못 탄 사람은 더 빨리 오는 걸 타고 10층으로 간다고 가정
if eupin[0]+oupin[0]>0 and etime<otime:
        eupout[5]=eupout[5]+eupin[0]+oupin[0]
        eupin[0]=eupin[0]+oupin[0]
        oupin[0]=0
if eupin[0]+oupin[0]>0 and otime<etime:
        oupout[5]=oupout[5]+eupin[0]+oupin[0]
        oupin[0]=eupin[0]+oupin[0]
        eupin[0]=0
#10층에서 못 탄 사람은 더 빨리 오는 걸 타고 1층으로 간다고 가정
if edwin[5]+odwin[5]>0 and etime<otime:
        edwout[0]=edwout[0]+edwin[5]+odwin[5]
        edwin[5]=edwin[5]+odwin[5]
        odwin[5]=0
if edwin[5]+odwin[5]>0 and otime<etime:
        odwout[0]=odwout[0]+edwin[5]+odwin[5]
        odwin[5]=edwin[5]+odwin[5]
        edwin[5]=0
#2~9층에서 못 탄 사람은 층수에 맞는 엘리베이터를 타고 1 or 10층으로 간다고 가정
for i in range(1,5):
    if eupin[i]>0:
        eupout[5]=eupout[5]+eupin[i]
    if edwin[i]>0:
        edwout[0]=edwout[0]+edwin[i]
    if oupin[i]>0:
        oupout[5]=oupout[5]+oupin[i]
    if odwin[i]>0:
        odwout[0]=odwout[0]+odwin[i]

In [43]:
if sum(eupin[0:]+edwin[0:]+oupin[0:]+odwin[0:])>0:
    eupinst=zeros((6,1))
    eupoutst=zeros((6,1))
    edwinst=zeros((6,1))
    edwoutst=zeros((6,1))
    oupinst=zeros((6,1))
    oupoutst=zeros((6,1))
    odwinst=zeros((6,1))
    odwoutst=zeros((6,1))
    for i in range(6):
        #올라가는 짝수엘베의 1,0
        if eupin[i]>=1:
            eupinst[i]=1
        if eupout[i]>=1:
            eupoutst[i]=1
        #올라가는 홀수엘베의 1,0
        if oupin[i]>=1:
            oupinst[i]=1
        if oupout[i]>=1:
            oupoutst[i]=1
    eupst=zeros((6,1))
    edwst=zeros((6,1))
    oupst=zeros((6,1))
    odwst=zeros((6,1))
    for i in range(6):
        #올라갈때 타거나 내리려는 사람이 있고, 엘베 안이 19명 이하라면 오픈
        if eupinst[i]+eupoutst[i]>0 and sum(eupin[:(i+1)])-sum(eupout[:(i+1)])<=19:
            eupst[i]=1
        if oupinst[i]+oupoutst[i]>0 and sum(oupin[:(i+1)])-sum(oupout[:(i+1)])<=19:
            oupst[i]=1
    for i in range(6):
        #내려가는 짝수엘베의 1,0
        if edwin[i]>=1:
            edwinst[i]=1
        if edwout[i]>=1:
            edwoutst[i]=1
        #내려가는 홀수엘베의 1,0
        if odwin[i]>=1:
            odwinst[i]=1
        if odwout[i]>=1:
            odwoutst[i]=1
    for i in range(6):
        #내려갈때 타거나 내리려는 사람이 있고, 엘베 안이 19명 이하라면 오픈
        if edwinst[i]+edwoutst[i]>0 and sum(edwin[(i+1):])-sum(edwout[(i+1):])<=19:
            edwst[i]=1
        if odwinst[i]+odwoutst[i]>0 and sum(odwin[(i+1):])-sum(odwout[(i+1):])<=19:
            odwst[i]=1
    eupf=[]
    edwf=[]
    oupf=[]
    odwf=[]
    for i in range(6):
        if eupst[i]==1:
            eupf.append(i+1)
        if edwst[i]==1:
            edwf.append(i+1)
        if oupst[i]==1:
            oupf.append(i+1)
        if odwst[i]==1:
            odwf.append(i+1)
    eupl=len(eupf)
    edwl=len(edwf)
    eupt=0
    edwt=0
    oupl=len(oupf)
    odwl=len(odwf)
    oupt=0
    odwt=0
    #open인층에서 다음 open인 층까지의 시간 계산
    for i in range(eupl-1):
        eupt=eupt+(eupf[i+1]-eupf[i]-1)*4+10
    for i in range(edwl-1):
        edwt=edwt+(edwf[i+1]-edwf[i]-1)*4+10
    for i in range(oupl-1):
        oupt=oupt+(oupf[i+1]-oupf[i]-1)*4+10
    for i in range(odwl-1):
        odwt=odwt+(odwf[i+1]-odwf[i]-1)*4+10
    edwst[5]=0
    odwst[5]=0
    eupop=0
    edwop=0
    oupop=0
    odwop=0
    #각 층에서 오픈이면 12초씩 추가
    for i in range(6):
        if eupst[i]==1:
            eupop=eupop+12
        if edwst[i]==1:
            edwop=edwop+12
        if oupst[i]==1:
            oupop=oupop+12
        if odwst[i]==1:
            odwop=odwop+12
    etime1=eupop+edwop+eupt+edwt
    otime1=oupop+odwop+oupt+odwt

In [44]:
time=max(etime+etime1,otime+otime1)
print(time)

NameError: name 'etime1' is not defined

In [45]:
time=max(etime,otime)
print(time)

186


In [ ]:
sum(eupin[0:]+edwin[0:]+oupin[0:]+odwin[0:])